### ISSUE TITLE
onetimesecret.com website not showing correctly...

### ISSUE THREAD

**Issue by SimplSam** [onetimesecret/onetimesecret#351]
After the recent maintenance (_23rd May_) the website is not showing correctly. Can't see normal style nor login text etc.
I have tried on 3 different browsers.

![OneTime Screenshot 2024-05-24](https://github.com/onetimesecret/onetimesecret/assets/25576011/f4bf1b2b-cf91-4999-88fa-7273d6d05b6d)

**Comment by xebia-progress** [comment]
Generate a random password is also broken:

Request URL:
https://onetimesecret.com/private/f6i7cyq8y652yrl2tlmvr5ivggwp4f3

Request Method:
GET

The status is **200** but the response is empty. 

<img width="1214" alt="image" src="https://github.com/onetimesecret/onetimesecret/assets/25327019/ca0e6698-83f2-4d1f-830b-7822249d61c0">

**Comment by elcrgo** [comment]
Can confirm. I was about to post the same issue. This service is not usable right now..

**Comment by jwilliams-shadowsoft** [comment]
Pregenerated links from yesterday yield a blank screen.

**Comment by jwilliams-shadowsoft** [comment]
Web site is now working correctly, seemingly. I did not test all features.

Thanks!

**Comment by techron227** [comment]
https://next.onetimesecret.com/ seems to work. Was on the usual site >> click about us >> click logo and ended up on a working page. I'm guessing it's OK to use?

**Comment by delano** [comment]
Taking a look now.

**Comment by delano** [comment]
I moved to a new server yesterday which involved updating the DNS. The app running on the new server was still generating links with the temporary next.onetimesecret.com subdomain, which is what you folks were seeing. I gracefully restarted the app on the new server about 10 mins ago and that's resolved now.

Thanks for the multiple reports and details. That helped speed up figuring it out what it was 🙏

**Comment by CarlGreenApps** [comment]
Create a secret loads to blank page.

**Comment by srogovtsev** [comment]
Unfortunately, still doesn't work: links pointing to https://onetimesecret.com/secret/... continue showing a blank page, start page isn't completely loaded.

If it's DNS, here's what the resolution looks like from my side:

```
Non-authoritative answer:
Name:    onetimesecret.com
Address:  94.130.151.241
```

**Comment by delano** [comment]
Thanks, looks like you're getting the new IP. The "old" (49.13.2.100) is still pointing to the old server which is still up and running. 

In any case, to try to replicate what you're seeing I connected to a VPN locally and tried opening the site. I can replicate the blank page issue so investigating now.

**Comment by delano** [comment]
It looks like there might have been an issue with the caddy configuration. I've made what I thought would be an arbitrary change and restarted but I'm continuing to monitor.
