### ISSUE TITLE
v0.16.1-rc2 image contains but does not serve fix in #527

### ISSUE THREAD

**Issue by alemonmk** [onetimesecret/onetimesecret#532]
Hi,
I tried the latest image and still see issue in #525, figure I should open a new issue here.
Looked around in the container, somehow there are double pack of assets in `/app/public/web/dist/assets` and I'm served the problematic one:
![圖片](https://github.com/user-attachments/assets/adbc6ca4-de70-48f5-b87b-3635beda1020)
![圖片](https://github.com/user-attachments/assets/bd8a067a-abf4-4ef6-b9c4-7465a14afbff)
I wondered why the assets are generated twice (or not cleaned up before build), looked into `vite.config.js`:
https://github.com/onetimesecret/onetimesecret/blob/5450dfe45e70fad50421b5d7733a73de48e4f101/vite.config.ts#L62-L66
Wait a minute... if `../` is the problem here I don't think the built assets would end up in the right place but they are at the right place.
Further check those old files are introduced in [commit 0450da2](https://github.com/onetimesecret/onetimesecret/commit/0450da2da592cccc3548aa9dd49b90a18b353e18), basically indicated that the output directory was not cleaned up and served your prebuilt assets instead of those built by GitHub Actions.
Maybe the next container build this issue will be really gone as you have rebuilt assets since, but I believe this is something that need your attention.

**Comment by delano** [comment]
Thanks for all the detail and good sleuthing. It's related to #525 and also #522 which should address the root cause. 

Basically right now in the absence of a second vite config that builds the assets without the cache-busting suffix, I've been manually updating and checking in the dist directory after each PR. The javascript front-end is new (only about a month old) and adds new system dependencies so I've been doing that as a short-term convenience for devs that work with the ruby codebase. 

There is a bug affecting your config which you note above: `base: '/'` should be `base: '/dist'. It's fixed in my current working branch ([510-link-domain](https://github.com/onetimesecret/onetimesecret/tree/510-link-domain)) which I'll be merging a bit later today and including in v0.16.1-RC3. 

https://github.com/onetimesecret/onetimesecret/blob/94f218e70f4e8dfe627ac300aec0f838c191a50b/vite.config.ts#L62-L65

**Comment by delano** [comment]
One thing I missed earlier was the specific cause of the duplicate asset files that you mentioned. There was a duplicate `COPY . .` command right at the end of the the Dockerfile. That's fixed now and will be in `develop` and the RC3 shortly.

**Comment by alemonmk** [comment]
Updated my container to RC3, it loaded the latest scripts but passphrase is still not working:
![圖片](https://github.com/user-attachments/assets/ac06f2aa-c51c-4fae-88e9-67f2cdc394e3)
The #527 fix still haven't landed:
![圖片](https://github.com/user-attachments/assets/62fc813f-9114-4f49-b528-ad6d80450e1c)
Checked the main.js, the `name` attribute is not there:
![圖片](https://github.com/user-attachments/assets/9d4ff4a2-ec65-445f-a1c6-1ba38681d387)

Dug deeper, it seems you didn't backport the change back when you separated privacy options out of SecretForm:
https://github.com/onetimesecret/onetimesecret/blob/2b38be6f627ee07b8088c93130fc62a7f1844aab/src/components/SecretFormPrivacyOptions.vue#L50-L58

**Comment by delano** [comment]
#feelsbadman.gif  Thanks so much for catching that. RC4 is building now.

**Comment by alemonmk** [comment]
Thanks, now it works perfectly!
